# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: azure/setup-kubectl@v1
      with:
        version: '<version>' # default is latest stable
      id: install
    - uses: azure/setup-helm@v1
      with:
        version: '<version>' # default is latest stable
      id: install
    - uses: vmware-tanzu/carvel-setup-action@v1
    - run: |
        ytt version
        kbld version
    - name: Tanzu Plugin Installation
      run: |
        tanzu plugin install --local cli all
    - name: Set env variable and proxy
      env:
        FIRST_NAME: 
        middle_name: The
        Last_Name: Octocat
    - name: Login to Tanzu Cluster
      run: |
        tanzu login --endpoint
    - name: Generate Kubeconfig
      run: |
        tanzu cluster kubeconfig get wrkld-az2-1-tkm-system-1
    - name: switch context
      run: |
        kcubectl config use-context tanzu-cli-wrkld-az2-1-tkm-system-1@wrkld-az2-1-tkm-system-1
    - name: Get Pods running in ems-sys Namespace
      run: |
        kubectl get pods -n ems-sys
    - name: Get Pods running in ems-sys Namespace
      run: |
        kubectl get pods -n ems-sys
        
    - name: Generate local package with HELM
      run: |
        helm package ./tgk-sampleapp-springboot-chart
        
    - name: switch context
      run: |
        kcubectl config use-context tanzu-cli-wrkld-az2-1-tkm-system-1@wrkld-az2-1-tkm-system-1
        
    - name: set context
      run: |
        kubectl config set-context --current --namespace=ems-sys
        
